- name: Deploy Next.js App
  hosts: ec2-instance
  become: yes
  tasks:
    
    # Actualizar los paquetes del sistema
    - name: Update server packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all installed packages to latest versions
      apt:
        upgrade: dist
        state: latest

    # Instalar dependencias de Node.js necesarias
    - name: Install missing Node.js dependencies
      apt:
        name:
          - node-agent-base
          - node-archy
          - node-cacache
          - node-chalk
          - node-cli-table3
          - node-columnify
          - node-cssesc
          - node-debug
          - node-emoji-regex
          - node-gyp
          - node-http-proxy-agent
          - node-https-proxy-agent
          - node-mkdirp
          - node-ms
          - node-nopt
          - node-normalize-package-data
          - node-npm-bundled
          - node-npm-normalize-package-bin
          - node-npm-package-arg
          - node-npmlog
          - node-postcss-selector-parser
          - node-read-package-json
          - node-rimraf
          - node-semver
          - node-string-width
          - node-strip-ansi
          - node-tar
          - node-validate-npm-package-name
          - node-which
        state: present

    # Instalar NVM y usarlo para instalar Node.js y npm
    - name: Install NVM (Node Version Manager)
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        source ~/.bashrc
        nvm install 18
        nvm use 18
        npm install -g npm@9.2.0

    # Instalar nginx
    - name: Install nginx
      apt:
        name: nginx
        state: present

    # Configurar nginx
    - name: Configure Nginx
      copy:
        dest: "/etc/nginx/sites-available/default"
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
      notify:
        - Restart Nginx

    # Reiniciar Nginx
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    # Verificar las versiones de Node.js y npm
    - name: Check installed Node.js version
      shell: node -v

    - name: Check installed npm version
      shell: npm -v