- name: Deploy Next.js App
  hosts: servers
  become: true  # Permite usar sudo

  tasks:
    - name: Update server packages
      apt:
        update_cache: yes

    - name: Fix broken packages
      command: apt-get install -f -y

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Remove old versions of nodejs and npm
      apt:
        name:
          - nodejs
          - npm
        state: absent

    - name: Add Node.js repository
      shell: curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

    - name: Install Node.js
      apt:
        name:
          - nodejs
        state: present

    - name: Install npm using n package manager
      shell: |
        curl -L https://www.npmjs.com/install.sh | sh
      args:
        executable: /bin/bash

    - name: Install pnpm
      shell: |
        curl -fsSL https://get.pnpm.io/install.sh | sh -
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        corepack enable
      args:
        executable: /bin/bash

    - name: Add pnpm to PATH permanently
      shell: echo 'export PATH="/home/ubuntu/.local/share/pnpm:$PATH"' >> /home/ubuntu/.bashrc
      args:
        executable: /bin/bash

    - name: Check if the repository exists
      stat:
        path: /home/ubuntu/app/frontend_cube_2025/.git  # Verifica si el directorio .git existe dentro del repo
      register: repo_stat

    - name: Git clone if repository does not exist
      git:
        repo: 'https://github.com/barbaralzb/frontend_cube_2025.git'
        dest: /home/ubuntu/app
        version: main  # O la rama que desees
        force: yes
      when: repo_stat.stat.exists == False

    - name: Git pull if repository exists
      git:
        repo: 'https://github.com/barbaralzb/frontend_cube_2025.git'
        dest: /home/ubuntu/app/frontend_cube_2025
        update: yes
        version: main  # O la rama que desees
        force: yes
      when: repo_stat.stat.exists == True

    - name: Install dependencies with pnpm
      shell: |
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        cd /home/ubuntu/app/frontend_cube_2025
        pnpm install --frozen-lockfile

    - name: Build the Next.js app
      shell: |
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        cd /home/ubuntu/app/frontend_cube_2025
        pnpm build

    - name: Install PM2 globally
      shell: npm install -g pm2

    - name: Start Next.js app with PM2
      shell: |
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        pm2 delete frontend-app || true
        cd /home/ubuntu/app/frontend_cube_2025
        pm2 start "pnpm start" --name "frontend-app"
        pm2 save
        sudo $(pm2 startup | tail -n 1)

    - name: Configure Nginx
      copy:
        dest: "/etc/nginx/sites-available/default"
        content: |
          server {
              listen 8080;
              server_name 15.237.116.116;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted