- name: Deploy Next.js App
  hosts: servers
  become: true  # Permite usar sudo

  tasks:
    - name: Update server packages
      apt:
        update_cache: yes

    - name: Fix broken packages
      command: apt-get install -f -y

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Remove old versions of nodejs
      apt:
        name: nodejs
        state: absent

    - name: Add Node.js repository
      shell: curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

    - name: Install Node.js
      apt:
        name:
          - nodejs
        state: present

    - name: Install npm (if necessary)
      apt:
        name:
          - npm
        state: present
      when: ansible_facts.packages.nodejs is not defined

    - name: Install pnpm
      shell: |
        curl -fsSL https://get.pnpm.io/install.sh | sh -
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        corepack enable
      args:
        executable: /bin/bash

    - name: Add pnpm to PATH permanently
      shell: echo 'export PATH="/home/ubuntu/.local/share/pnpm:$PATH"' >> /home/ubuntu/.bashrc
      args:
        executable: /bin/bash

    - name: Clone or update repo
      git:
        repo: "https://github.com/barbaralzb/frontend_cube_2025.git"
        dest: "/home/ubuntu/app"
        version: main
        force: yes

    - name: Install dependencies with pnpm
      shell: |
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        cd /home/ubuntu/app/frontend_cube_2025
        pnpm install --frozen-lockfile

    - name: Build the Next.js app
      shell: |
        export PATH="/home/ubuntu/.local/share/pnpm:$PATH"
        cd /home/ubuntu/app/frontend_cube_2025
        pnpm build

    - name: Install PM2 globally
      shell: npm install -g pm2

    - name: Start Next.js app wi