# name: Deploy Next.js a AWS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout del código
#         uses: actions/checkout@v4

#       - name: Configurar SSH
#         run: |
#           echo "${{ secrets.AWS_RSA_PRIVATE_KEY }}" > private_key.pem
#           chmod 600 private_key.pem

#       - name: Instalar Ansible
#         run: sudo apt update &&  sudo apt-get && update sudo apt-get upgrade && sudo apt-get install -f && sudo apt install -y ansible

#       - name: Ejecutar Ansible para desplegar Next.js
#         run: ansible-playbook -i inventory.ini ansible/playbooks/deploy.yml