name: Deploy Next.js to AWS EC2 with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_RSA_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Ansible Playbook (Skip Host Key Verification)
        run: |
          export ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no"
          ansible-playbook -i inventory.ini playbook.yml --private-key private_key.pem

      - name: Cleanup SSH Key
        run: rm -f private_key.pem
